<a href="https://colab.research.google.com/github/protagonistforever/analysis/blob/main/mlr.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
import numpy as np

In [ ]:
from sklearn import linear_model

In [ ]:
area=[2500,3000,3200,3500,4000,4100]

In [ ]:
bedrooms=[3.0,4.0,None,3.0,5.0,6.0]

In [ ]:
age=[20,15,18,30,8,8]

In [ ]:
price=[550000,565000,610000,505000,760000,810000]

In [ ]:
df=pd.DataFrame({"area":area,"bedrooms":bedrooms,"age":age,"price":price})

In [ ]:
df

area  bedrooms  age   price
0  2500       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3500       3.0   30  505000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [ ]:
import math

In [ ]:
df.bedrooms.median()

4.0

In [ ]:
df.bedrooms=df.bedrooms.fillna(df.bedrooms.median())

In [ ]:

df

area  bedrooms  age   price
0  2500       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3500       3.0   30  505000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [ ]:
model=linear_model.LinearRegression()

In [ ]:
model.fit(df.drop("price",axis="columns"),df.price)

LinearRegression()

In [ ]:
model.predict([[3000,3,1]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([672380.89118396])

In [ ]:
model.coef_

array([   59.06956095, 35498.98357361, -6652.02389576])

In [ ]:
model.intercept_

395327.28150727134

In [ ]:
model.predict([[300,2,1]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([477394.09304391])

In [ ]:
exp=[None,None,5,2,7,3,10,11]

In [ ]:
test_score=[8,8,6,10,9,7,None,7]

In [ ]:
int_sc=[9,6,7,10,6,10,7,8]

In [ ]:
salary=[50000,45000,60000,65000,70000,62000,72000,80000]

In [ ]:
df1=pd.DataFrame({"experience":exp,"test_score":test_score,"int_score":int_sc,"salary":salary})
df1

experience  test_score  int_score  salary
0         NaN         8.0          9   50000
1         NaN         8.0          6   45000
2         5.0         6.0          7   60000
3         2.0        10.0         10   65000
4         7.0         9.0          6   70000
5         3.0         7.0         10   62000
6        10.0         NaN          7   72000
7        11.0         7.0          8   80000

In [ ]:
df1.experience=df1.experience.fillna(df1.experience.mean())
df1.test_score=df1.test_score.fillna(df1.test_score.mean())
df1

experience  test_score  int_score  salary
0    6.333333    8.000000          9   50000
1    6.333333    8.000000          6   45000
2    5.000000    6.000000          7   60000
3    2.000000   10.000000         10   65000
4    7.000000    9.000000          6   70000
5    3.000000    7.000000         10   62000
6   10.000000    7.857143          7   72000
7   11.000000    7.000000          8   80000

In [ ]:
model1=linear_model.LinearRegression()

In [ ]:
model1.fit(df1.drop('salary',axis='columns'),df1.salary)

LinearRegression()

In [ ]:
model1.predict([[2,9,6]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([47738.89104313])

In [ ]:
model1.predict([[12,10,10]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([86424.66795913])

In [ ]:
import pickle

In [ ]:
with open("model_pickle", "wb") as file:
  pickle.dump(model,file)

In [ ]:
with open("model_pickle", "rb") as f:
  mp=pickle.load(f)

In [ ]:
mp.coef_

array([   59.06956095, 35498.98357361, -6652.02389576])

In [ ]:
mp.predict([[10,10,10]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([684387.57389537])

In [ ]:
from sklearn.externals import joblib

ImportError: cannot import name 'joblib' from 'sklearn.externals' (/usr/local/lib/python3.10/dist-packages/sklearn/externals/__init__.py)

In [ ]:
import joblib

In [ ]:
joblib.dump(model,"model_joblib")

['model_joblib']

In [ ]:
mj=joblib.load("model_joblib")

In [ ]:
mj.coef_

array([   59.06956095, 35498.98357361, -6652.02389576])

In [ ]:
df=pd.read_csv("homeprices.csv")

In [ ]:
df.shape

(13, 3)

In [ ]:
df


town  area   price
0   monroe township  2600  550000
1   monroe township  3000  565000
2   monroe township  3200  610000
3   monroe township  3600  680000
4   monroe township  4000  725000
5      west windsor  2600  585000
6      west windsor  2800  615000
7      west windsor  3300  650000
8      west windsor  3600  710000
9       robinsville  2600  575000
10      robinsville  2900  600000
11      robinsville  3100  620000
12      robinsville  3600  695000

In [ ]:
dum=pd.get_dummies(df.town)
dum

monroe township  robinsville  west windsor
0                 1            0             0
1                 1            0             0
2                 1            0             0
3                 1            0             0
4                 1            0             0
5                 0            0             1
6                 0            0             1
7                 0            0             1
8                 0            0             1
9                 0            1             0
10                0            1             0
11                0            1             0
12                0            1             0

In [ ]:
df_dum=pd.concat([df,dum],axis="columns")

In [ ]:
df_dum

town  area   price  monroe township  robinsville  west windsor
0   monroe township  2600  550000                1            0             0
1   monroe township  3000  565000                1            0             0
2   monroe township  3200  610000                1            0             0
3   monroe township  3600  680000                1            0             0
4   monroe township  4000  725000                1            0             0
5      west windsor  2600  585000                0            0             1
6      west windsor  2800  615000                0            0             1
7      west windsor  3300  650000                0            0             1
8      west windsor  3600  710000                0            0             1
9       robinsville  2600  575000                0            1             0
10      robinsville  2900  600000                0            1             0
11      robinsville  3100  620000                0            1             0
12      robinsville  3600  695000                0            1             0

In [ ]:
x=df_dum.drop(['town','west windsor'],axis="columns")

In [ ]:
x

area   price  monroe township  robinsville
0   2600  550000                1            0
1   3000  565000                1            0
2   3200  610000                1            0
3   3600  680000                1            0
4   4000  725000                1            0
5   2600  585000                0            0
6   2800  615000                0            0
7   3300  650000                0            0
8   3600  710000                0            0
9   2600  575000                0            1
10  2900  600000                0            1
11  3100  620000                0            1
12  3600  695000                0            1

In [ ]:
y=x.drop("price",axis="columns")

In [ ]:
y

area  monroe township  robinsville
0   2600                1            0
1   3000                1            0
2   3200                1            0
3   3600                1            0
4   4000                1            0
5   2600                0            0
6   2800                0            0
7   3300                0            0
8   3600                0            0
9   2600                0            1
10  2900                0            1
11  3100                0            1
12  3600                0            1

In [ ]:
z=x.price

In [ ]:
z

0     550000
1     565000
2     610000
3     680000
4     725000
5     585000
6     615000
7     650000
8     710000
9     575000
10    600000
11    620000
12    695000
Name: price, dtype: int64

In [ ]:
model=linear_model.LinearRegression()
model.fit(y,z)

LinearRegression()

In [ ]:
model.predict([[3400,0,0]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([681241.66845839])

In [ ]:
model.predict([[3400,0,1]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([666914.10449365])

In [ ]:
model.predict([[3400,1,0]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([641227.69296925])

In [ ]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()

In [ ]:
dfle=df

In [ ]:
dfle.town=le.fit_transform(dfle.town)
dfle


town  area   price
0      0  2600  550000
1      0  3000  565000
2      0  3200  610000
3      0  3600  680000
4      0  4000  725000
5      2  2600  585000
6      2  2800  615000
7      2  3300  650000
8      2  3600  710000
9      1  2600  575000
10     1  2900  600000
11     1  3100  620000
12     1  3600  695000

In [ ]:
x=dfle[["town","area"]].values

In [ ]:
x

array([[   0, 2600],
       [   0, 3000],
       [   0, 3200],
       [   0, 3600],
       [   0, 4000],
       [   2, 2600],
       [   2, 2800],
       [   2, 3300],
       [   2, 3600],
       [   1, 2600],
       [   1, 2900],
       [   1, 3100],
       [   1, 3600]])

In [ ]:
y=dfle.price.values

In [ ]:
from sklearn.preprocessing import OneHotEncoder

In [ ]:
ohe=OneHotEncoder(categories="auto")

In [ ]:
ohe.fit_transform(x).toarray()

array([[1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.]])